### ISSUE TITLE
Not getting an address

### ISSUE THREAD

**Issue by wicadmin** [dusansusic/kubernetes-traefik#4]
```
kubectl --namespace=traefik describe ingress traefik-dashboard-ingress
Name:             traefik-dashboard-ingress
Namespace:        traefik
Address:          
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host                    Path  Backends
  ----                    ----  --------
  traefik-ui.example.com  
                          /   traefik-dashboard:8080 (<none>)
Annotations:
  kubectl.kubernetes.io/last-applied-configuration:  {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"traefik","traefik.ingress.kubernetes.io/frontend-entry-points":"http,https","traefik.ingress.kubernetes.io/redirect-entry-point":"https","traefik.ingress.kubernetes.io/redirect-permanent":"true"},"name":"traefik-dashboard-ingress","namespace":"traefik"},"spec":{"rules":[{"host":"traefik-ui.example.com","http":{"paths":[{"backend":{"serviceName":"traefik-dashboard","servicePort":8080},"path":"/"}]}}]}}

  kubernetes.io/ingress.class:                          traefik
  traefik.ingress.kubernetes.io/frontend-entry-points:  http,https
  traefik.ingress.kubernetes.io/redirect-entry-point:   https
  traefik.ingress.kubernetes.io/redirect-permanent:     true
Events:                                                 <none>
```

**Comment by dusansusic** [comment]
can you explain what's your issue?

**Comment by jonathanprado** [comment]
Hi,  I have the exactly same problem that @wicadmin 

<pre>
$ kubectl --namespace=traefik describe ingress traefik-dashboard-ingress
Name:             traefik-dashboard-ingress
Namespace:        traefik
Address:          
Default backend:  default-http-backend:80 (<none>)
Rules:
  Host                    Path  Backends
  ----                    ----  --------
  traefik-ui.example.com  
                          /   traefik-dashboard:8080 (<none>)
Annotations:
  kubectl.kubernetes.io/last-applied-configuration:  {"apiVersion":"extensions/v1beta1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"traefik","traefik.ingress.kubernetes.io/frontend-entry-points":"http,https","traefik.ingress.kubernetes.io/redirect-entry-point":"https","traefik.ingress.kubernetes.io/redirect-permanent":"true"},"name":"traefik-dashboard-ingress","namespace":"traefik"},"spec":{"rules":[{"host":"traefik-ui.example.com","http":{"paths":[{"backend":{"serviceName":"traefik-dashboard","servicePort":8080},"path":"/"}]}}]}}

  kubernetes.io/ingress.class:                          traefik
  traefik.ingress.kubernetes.io/frontend-entry-points:  http,https
  traefik.ingress.kubernetes.io/redirect-entry-point:   https
  traefik.ingress.kubernetes.io/redirect-permanent:     true
Events:                                                 <none>
</pre>

<pre>
$ kubectl get services --all-namespaces |grep traefik
traefik       traefik                  LoadBalancer   10.102.80.20     <pending>     80:31522/TCP,443:31482/TCP       56s
traefik       traefik-dashboard        ClusterIP      10.100.1.10      <none>        8080/TCP                         56s
</pre>


<pre>
$ kubectl get pods
traefik       traefik-ingress-controller-855asd88b-gp7qr   0/1     ContainerCreating   0          106m
traefik       traefik-ingress-controller-855asd988b-rdkj2   0/1     ContainerCreating   0          106m
</pre>

I have been testing curl to external ports but don't receive any data...

**Comment by dusansusic** [comment]
Your pods are not started at all.
