### ISSUE TITLE
secret tls namespace

### ISSUE THREAD

**Issue by ericsullivan** [dusansusic/kubernetes-traefik#5]
Thanks for the tutorial. I'm working through a K8S setup for the first time and your documentation has been helpful.

I was getting an error that the secret traefik-ui-tls-cert could not be found. According to the [docs](https://kubernetes.io/docs/concepts/configuration/secret/#restrictions):
"Secret API objects reside in a namespace. They can only be referenced by pods in that same namespace."

I adjusted the command to `kubectl create secret tls traefik-ui-tls-cert --key k8s/ssl/tls.key --cert k8s/ssl/tls.crt --namespace traefik`

**Comment by habibiefaried** [comment]
I'm about to give PR about this. This is correct

**Comment by dusansusic** [comment]
You can create tls certificate on this way or encode cert and key and put them into `tls_secret.yaml`.
